### ISSUE TITLE
pull data on how many of each role is in each toolkit/sakai site

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/learn.duke#171]

**Comment by swwalker** [comment]
@profmikegreene, @ewendland23 - do we have this data in Github anywhere?

**Comment by swwalker** [comment]
[tk_member_types.xlsx](https://github.com/DukeLearningInnovation/learn.duke/files/2124377/tk_member_types.xlsx)

For each course it has:
TK id    - Toolkit ID
name   - Toolkit name
type     - Toolkit type (we have 3- 1: course, 2: adhoc or non-course, 3: non-siss course (some horrible thing to support old Blackboard sites)
create_date    - when this toolkit was originated
n_tools – the number of associated tools.
 
And then there are the totals for each role.  All course roles are _1, non-course _2 and non-siss _3. I colored the ‘roll up’ groups because no one assigns people to those, they are composites of other groups.
 
Here is the TLDR; version:
 
For courses - 
Instructors: 22251       
Managers: 30465        
TAs: 395                      
Developer: 11686       
Mentor: 14885                        
Student: 473850         
Visitor: 4106    
Auditor: 29370                        
 
For adhoc -
Admin 19957   
Contributor 48043      
Viewer 18966
