### ISSUE TITLE
Can a toolkit have multiple instances of the same app?

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/learn.duke#194]
initially we proposed allowing multiple instances of a resource per Toolkit but all of the initial resources are ‘singletons’ or, can only have one instance.

So, the question – Do we need to allow multiple instances.  Like 2 Sakais, or Wordpress sites?  I guess they may have multiple ‘URLs’?  But does it make sense for any of the others?

**Comment by profmikegreene** [comment]
Can we design the integrations to allow multiple instances but not expose that capability to users for now? Because it has always been singleton, we have never asked users how they might use multiple instances and as a result, we don't have any use cases at hand. I could see it being useful for apps like Warpwire that allow student creation. So you could have an app that was the video lessons library and an app that was the student dropbox for video assignments.

Could the decision be made per app instead of uniform across the system?

**Comment by ewendland23** [comment]
Sure, that is how it is currently.  We allow multiple in our Data Model, and each resource(tool) indicates if it is a singleton or not.  Currently all are singletons.  So we won't change that.
